# Generated by Django 3.2.3 on 2021-05-25 23:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='postedTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 25, 23, 21, 59, 619184, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='userName',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
