# Generated by Django 3.2.3 on 2021-05-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0006_auto_20210526_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='', max_length=400),
        ),
    ]
