# Generated by Django 3.2.3 on 2021-05-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0009_auto_20210526_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='price',
            field=models.IntegerField(default='5'),
        ),
    ]
