# Generated by Django 3.2.3 on 2021-05-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0010_comment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='price',
        ),
    ]
