# Generated by Django 3.2.3 on 2021-06-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0014_alter_networking_typeofuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizzAval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(max_length=200)),
                ('beAguide', models.BooleanField(choices=[(True, 'Sim!'), (False, 'Siiiim!')])),
                ('numberOfApps', models.IntegerField()),
                ('percentageOfPay', models.IntegerField()),
                ('availablePlataforms', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')])),
                ('howManyDevs', models.IntegerField()),
                ('animations', models.IntegerField()),
                ('audioQuestion', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')])),
                ('disciplina', models.CharField(max_length=200)),
                ('monthsProject', models.IntegerField(default='12')),
            ],
        ),
    ]
