# Generated by Django 3.2.3 on 2021-06-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0016_rename_monthsproject_quizzaval_diff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clareza', models.IntegerField(default='12')),
                ('rigor', models.IntegerField(default='12')),
                ('precisao', models.IntegerField(default='12')),
                ('profundidade', models.IntegerField(default='12')),
                ('amplitude', models.IntegerField(default='12')),
                ('logica', models.IntegerField(default='12')),
                ('significancia', models.IntegerField(default='12')),
                ('originalidade', models.IntegerField(default='12')),
                ('sugestao', models.TextField(default='', max_length=400)),
            ],
        ),
    ]
